version: "3.8"

services:
  db:
    image: postgres:17
    container_name: shiftplanner-db
    environment:
      POSTGRES_DB: shiftplanner
      POSTGRES_USER: shiftplanner
      POSTGRES_PASSWORD: shiftplanner
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: shiftplanner-app
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8686:8686"